### ISSUE TITLE
Issues with eval_one Function and Guidance on Using lfcc ShallowCNN Model

### ISSUE THREAD

**Issue by VictorMEY** [MarkHershey/AudioDeepFakeDetection#6]
Hi,

I've made some modifications to the code to ensure compatibility with Windows, specifically addressing the Sox dependency with torchaudio by using Sox independently. Other than that, I've kept the original setup intact.

However, I've encountered an issue when using the eval_one function. Every audio input, whether genuine or fake, is consistently classified as fake (output always equals 1). This behavior is observed even when testing on authentic audio files.

I'd like to understand the correct procedure to utilize the lfcc ShallowCNN model that you've provided for evaluating audio files. Since I don't have an NVIDIA GPU, training is quite time-intensive for me, and I'm keen on testing the pre-trained model you've developed on new RVC voice-generated samples and others.

Any guidance on how to successfully test the model would be greatly appreciated. Thank you!

**Comment by VictorMEY** [comment]
Look here, I used a real file from your dataset and it's given me a 1, and another value when i'm debugging. I can't make it work, and I would love your help :'( 

```
``PS C:\Users\ZQ833RM\code\AudioDeepFakeDetection> python train.py --feature_classname lfcc --model_classname ShallowCNN --restore --eval_one --test_file "/LJ042-0222.wav"
>>>>> Starting experiment: ShallowCNN_lfcc_I
2023-10-31 09:17:31,927 - INFO - Evaluating model: ShallowCNN
2023-10-31 09:17:31,927 - INFO - Input feature : lfcc
2023-10-31 09:17:31,927 - INFO - Model kwargs  : {
  "in_features": 1,
  "out_dim": 1,
  "device": "cpu"
}
2023-10-31 09:17:31,927 - INFO - Loading data...
2023-10-31 09:17:31,927 - INFO - Testing model on  1 audio files.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1113, in emit    
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode    
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 380-381: character maps to <undefined>
Call stack:
  File "C:\Users\ZQ833RM\code\AudioDeepFakeDetection\train.py", line 751, in <module>
    main()
  File "C:\Users\ZQ833RM\code\AudioDeepFakeDetection\train.py", line 727, in main
    experiment(
  File "C:\Users\ZQ833RM\code\AudioDeepFakeDetection\train.py", line 535, in experiment
    eval_one_f(
  File "C:\Users\ZQ833RM\code\AudioDeepFakeDetection\train.py", line 489, in eval_one_f
    LOGGER.info(f"Model summary:\n{summary_str}")
Message: 'Model summary:\n==========================================================================================\nLayer (type:depth-idx)
      Output Shape              Param #\n==========================================================================================\nShallowCNN
                     [256, 1]                  --\n├─Conv2d: 1-1                            [256, 32, 39, 971]        544\n├─MaxPool2d: 1-2
           [256, 32, 19, 485]        --\n├─Conv2d: 1-3                            [256, 48, 17, 483]        38,448\n├─MaxPool2d: 1-4
    [256, 48, 8, 241]         --\n├─Conv2d: 1-5                            [256, 64, 7, 240]         49,216\n├─MaxPool2d: 1-6                         [256, 64, 3, 120]         --\n├─Conv2d: 1-7                            [256, 128, 4, 119]        65,664\n├─MaxPool2d: 1-8                         [256, 128, 2, 59]         --\n├─Linear: 1-9                            [256, 128]                1,933,440\n├─Linear: 1-10                           [256, 1]      
            129\n==========================================================================================\nTotal params: 2,087,441\nTrainable params: 2,087,441\nNon-trainable params: 0\nTotal mult-adds (Units.GIGABYTES): 115.76\n==========================================================================================\nInput size (MB): 39.81\nForward/backward pass size (MB): 3634.20\nParams size (MB): 8.35\nEstimated Total Size (MB): 3682.37\n=========================================================================================='
Arguments: ()
2023-10-31 09:17:35,504 - INFO - Model summary:
==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
ShallowCNN                               [256, 1]                  --
├─Conv2d: 1-1                            [256, 32, 39, 971]        544
├─MaxPool2d: 1-2                         [256, 32, 19, 485]        --
├─Conv2d: 1-3                            [256, 48, 17, 483]        38,448
├─MaxPool2d: 1-4                         [256, 48, 8, 241]         --
├─Conv2d: 1-5                            [256, 64, 7, 240]         49,216
├─MaxPool2d: 1-6                         [256, 64, 3, 120]         --
├─Conv2d: 1-7                            [256, 128, 4, 119]        65,664
├─MaxPool2d: 1-8                         [256, 128, 2, 59]         --
├─Linear: 1-9                            [256, 128]                1,933,440
├─Linear: 1-10                           [256, 1]                  129
==========================================================================================
Total params: 2,087,441
Trainable params: 2,087,441
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 115.76
==========================================================================================
Forward/backward pass size (MB): 3634.20
Params size (MB): 8.35
Estimated Total Size (MB): 3682.37
==========================================================================================
2023-10-31 09:17:35,533 - INFO - Loaded checkpoint from epoch 16
13.940683364868164
0.9999991655349731
>>>>> Experiment Done: ShallowCNN_lfcc_I
PS C:\Users\ZQ833RM\code\AudioDeepFakeDetection> python train.py --feature_classname lfcc --model_classname ShallowCNN --restore --eval_one --test_file "LJ042-0222.wav" --debug
>>>>> Starting experiment: debug
2023-10-31 09:21:21,497 - INFO - Evaluating model: ShallowCNN
2023-10-31 09:21:21,498 - INFO - Input feature : lfcc
2023-10-31 09:21:21,498 - INFO - Model kwargs  : {
  "in_features": 1,
  "out_dim": 1,
  "device": "cpu"
}
2023-10-31 09:21:21,500 - INFO - Loading data...
2023-10-31 09:21:21,501 - INFO - Testing model on  1 audio files.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode    
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 380-381: character maps to <undefined>
Call stack:
  File "C:\Users\ZQ833RM\code\AudioDeepFakeDetection\train.py", line 751, in <module>
    main()
  File "C:\Users\ZQ833RM\code\AudioDeepFakeDetection\train.py", line 727, in main
    experiment(
  File "C:\Users\ZQ833RM\code\AudioDeepFakeDetection\train.py", line 535, in experiment
    eval_one_f(
  File "C:\Users\ZQ833RM\code\AudioDeepFakeDetection\train.py", line 489, in eval_one_f
    LOGGER.info(f"Model summary:\n{summary_str}")
Message: 'Model summary:\n==========================================================================================\nLayer (type:depth-idx)
      Output Shape              Param #\n==========================================================================================\nShallowCNN
                     [256, 1]                  --\n├─Conv2d: 1-1                            [256, 32, 39, 971]        544\n├─MaxPool2d: 1-2
           [256, 32, 19, 485]        --\n├─Conv2d: 1-3                            [256, 48, 17, 483]        38,448\n├─MaxPool2d: 1-4
    [256, 48, 8, 241]         --\n├─Conv2d: 1-5                            [256, 64, 7, 240]         49,216\n├─MaxPool2d: 1-6                         [256, 64, 3, 120]         --\n├─Conv2d: 1-7                            [256, 128, 4, 119]        65,664\n├─MaxPool2d: 1-8                         [256, 128, 2, 59]         --\n├─Linear: 1-9                            [256, 128]                1,933,440\n├─Linear: 1-10                           [256, 1]      
            129\n==========================================================================================\nTotal params: 2,087,441\nTrainable params: 2,087,441\nNon-trainable params: 0\nTotal mult-adds (Units.GIGABYTES): 115.76\n==========================================================================================\nInput size (MB): 39.81\nForward/backward pass size (MB): 3634.20\nParams size (MB): 8.35\nEstimated Total Size (MB): 3682.37\n=========================================================================================='
Arguments: ()
2023-10-31 09:21:25,212 - INFO - Model summary:
==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
ShallowCNN                               [256, 1]                  --
├─Conv2d: 1-1                            [256, 32, 39, 971]        544
├─MaxPool2d: 1-2                         [256, 32, 19, 485]        --
├─Conv2d: 1-3                            [256, 48, 17, 483]        38,448
├─MaxPool2d: 1-4                         [256, 48, 8, 241]         --
├─Conv2d: 1-5                            [256, 64, 7, 240]         49,216
├─MaxPool2d: 1-6                         [256, 64, 3, 120]         --
├─Conv2d: 1-7                            [256, 128, 4, 119]        65,664
├─MaxPool2d: 1-8                         [256, 128, 2, 59]         --
├─Linear: 1-9                            [256, 128]                1,933,440
├─Linear: 1-10                           [256, 1]                  129
==========================================================================================
Total params: 2,087,441
Trainable params: 2,087,441
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 115.76
==========================================================================================
Input size (MB): 39.81
Forward/backward pass size (MB): 3634.20
Params size (MB): 8.35
Estimated Total Size (MB): 3682.37
==========================================================================================
-0.06852015852928162
0.48287662863731384
>>>>> Experiment Done: debug

**Comment by MarkHershey** [comment]
Hi @VictorMEY , the `eval_one` function/argument is not in my original code, did you get the code from someone else?

**Comment by jamestiotio** [comment]
Hi there @VictorMEY, our [`train.py` file](https://github.com/MarkHershey/AudioDeepFakeDetection/blob/master/train.py) does not contain an `eval_one_f` function.

I am assuming that you are using the code developed by [a fork](https://github.com/PlayerBerny12/AudioDeepFakeDetection) of our repository, which does have an `eval_one_f` function in [their `train.py` file](https://github.com/PlayerBerny12/AudioDeepFakeDetection/blob/master/train.py#L391).

Please raise an issue on the other repository instead as it is the more appropriate venue. Closing this issue as invalid.
