### ISSUE TITLE
evaluate_error

### ISSUE THREAD

**Issue by pradeepkc11** [MarkHershey/AudioDeepFakeDetection#7]
when i run the evaluation code it is showing this error

2023-11-23 12:08:00,216 - ERROR - 'bool' object is not callable
Traceback (most recent call last):
  File "/home/pradeep/AudioDeepFakeDetection/train.py", line 593, in main
    experiment(
  File "/home/pradeep/AudioDeepFakeDetection/train.py", line 430, in experiment
    eval_only(
TypeError: 'bool' object is not callable

**Comment by pradeepkc11** [comment]
i have changed the eval_only function to eval_on it will fix the error
